name: Update GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  stats:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=usamajavaid81&show_icons=true&theme=tokyonight&include_all_commits=true
          path: profile/stats.svg
          git_push: true

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=usamajavaid81&layout=compact&theme=tokyonight
          path: profile/top-langs.svg
          git_push: true
